//! 物品附加数据（NBT）的键名表。
//!
//! 两套语法都收录，因为两条都还能用：
//! - **物品组件**（1.20.5 起）写成 `diamond_sword[minecraft:enchantments={...}]`；
//! - **旧式 NBT** 写成 `diamond_sword{Enchantments:[{id:"sharpness",lvl:5}]}`。
//!
//! 这份表用于两件事：输入 `[` / `{` 时的补全，以及把玩家的写法概括成中文反馈。

/// 现代物品组件 `物品[组件=值, ...]`
pub(crate) const ITEM_COMPONENTS: &[(&str, &str)] = &[
    ("minecraft:attribute_modifiers", "属性修饰符"),
    ("minecraft:banner_patterns", "旗帜图案"),
    ("minecraft:base_color", "盾牌底色"),
    ("minecraft:bees", "蜂巢内的蜜蜂"),
    ("minecraft:block_entity_data", "方块实体数据"),
    ("minecraft:block_state", "方块状态"),
    ("minecraft:blocks_attacks", "格挡属性"),
    ("minecraft:break_sound", "破坏音效"),
    ("minecraft:bucket_entity_data", "桶内实体数据"),
    ("minecraft:can_break", "可破坏的方块"),
    ("minecraft:can_place_on", "可放置的方块"),
    ("minecraft:charged_projectiles", "装填的弹射物"),
    ("minecraft:consumable", "消耗品属性"),
    ("minecraft:container", "容器内容物"),
    ("minecraft:container_loot", "容器战利品表"),
    ("minecraft:creative_slot_lock", "锁定创造模式槽位"),
    ("minecraft:custom_data", "自定义数据"),
    ("minecraft:custom_model_data", "自定义模型数据"),
    ("minecraft:custom_name", "自定义名称"),
    ("minecraft:damage", "已损耗耐久"),
    ("minecraft:damage_resistant", "伤害免疫"),
    ("minecraft:death_protection", "死亡保护"),
    ("minecraft:debug_stick_state", "调试棒状态"),
    ("minecraft:dyed_color", "染色颜色"),
    ("minecraft:enchantable", "可附魔"),
    ("minecraft:enchantment_glint_override", "附魔光效覆盖"),
    ("minecraft:enchantments", "附魔"),
    ("minecraft:entity_data", "实体数据"),
    ("minecraft:equippable", "可装备"),
    ("minecraft:fire_resistant", "抗火"),
    ("minecraft:food", "食物属性"),
    ("minecraft:glider", "滑翔"),
    ("minecraft:hide_tooltip", "隐藏提示"),
    ("minecraft:instrument", "山羊角乐器"),
    ("minecraft:intangible_projectile", "无形弹射物"),
    ("minecraft:item_model", "物品模型"),
    ("minecraft:item_name", "物品名称"),
    ("minecraft:jukebox_playable", "唱片曲目"),
    ("minecraft:lock", "容器锁"),
    ("minecraft:lore", "物品描述"),
    ("minecraft:map_color", "地图颜色"),
    ("minecraft:map_decorations", "地图标记"),
    ("minecraft:map_id", "地图编号"),
    ("minecraft:max_damage", "最大耐久"),
    ("minecraft:max_stack_size", "最大堆叠数"),
    ("minecraft:minimum_attack_charge", "最小攻击蓄力"),
    ("minecraft:note_block_sound", "头颅音效"),
    ("minecraft:ominous_bottle_amplifier", "不祥之瓶等级"),
    ("minecraft:pot_decorations", "饰纹陶罐碎片"),
    ("minecraft:potion_contents", "药水内容"),
    ("minecraft:profile", "玩家头颅档案"),
    ("minecraft:provides_banner_patterns", "提供旗帜图案"),
    ("minecraft:provides_trim_material", "提供纹饰材料"),
    ("minecraft:rarity", "稀有度"),
    ("minecraft:recipes", "解锁配方"),
    ("minecraft:repair_cost", "修复惩罚"),
    ("minecraft:stored_enchantments", "附魔书附魔"),
    ("minecraft:suspicious_stew_effects", "谜之炖菜效果"),
    ("minecraft:tool", "工具属性"),
    ("minecraft:tooltip_style", "提示样式"),
    ("minecraft:trim", "盔甲纹饰"),
    ("minecraft:unbreakable", "无法破坏"),
    ("minecraft:use_cooldown", "使用冷却"),
    ("minecraft:use_remainder", "使用后残留物"),
    ("minecraft:weapon", "武器属性"),
    ("minecraft:writable_book_content", "书与笔内容"),
    ("minecraft:written_book_content", "成书内容"),
];

/// NBT 键名表：既用于物品的旧式 `物品{Key: value}`（1.20.4 及更早的写法），
/// 也用于实体的 `{IsBaby:1b}`（`/summon`、`/data merge`）与方块 NBT。
pub(crate) const LEGACY_NBT_KEYS: &[(&str, &str)] = &[
    // ── 物品 ──
    ("Enchantments", "附魔"),
    ("StoredEnchantments", "附魔书附魔"),
    ("display", "展示信息（名称 / 描述 / 颜色）"),
    ("AttributeModifiers", "属性修饰符"),
    ("Unbreakable", "无法破坏"),
    ("Damage", "已损耗耐久"),
    ("RepairCost", "修复惩罚"),
    ("CustomModelData", "自定义模型数据"),
    ("SkullOwner", "头颅主人"),
    ("ChargedProjectiles", "装填的弹射物"),
    ("BlockEntityTag", "方块实体数据"),
    ("BlockStateTag", "方块状态"),
    ("EntityTag", "实体数据"),
    ("BucketVariantTag", "桶内实体变体"),
    ("Potion", "药水类型"),
    ("CustomPotionEffects", "自定义药水效果"),
    ("CustomPotionColor", "药水颜色"),
    ("HideFlags", "隐藏标记"),
    ("CanDestroy", "可破坏的方块"),
    ("CanPlaceOn", "可放置的方块"),
    ("title", "成书标题"),
    ("author", "成书作者"),
    ("pages", "成书页码"),
    ("generation", "成书版本"),
    ("map", "地图编号"),
    ("Fireworks", "烟花效果"),
    ("Explosion", "烟花爆炸"),
    ("FireworkStars", "烟花爆裂"),
    ("Bees", "蜂巢内的蜜蜂"),
    ("Lock", "容器锁"),
    ("Items", "容器内容物"),
    ("LootTable", "战利品表"),
    ("trim", "盔甲纹饰"),
    ("effects", "谜之炖菜效果"),
    ("Charged", "弩已装填"),
    ("Amplifier", "不祥之瓶等级"),
    ("Recipes", "解锁配方"),
    ("AdditionalTradeCost", "额外交易花费"),
    ("BlockEntityData", "方块实体数据"),
    // ── 实体（`/summon`、`/data merge entity`） ──
    ("IsBaby", "幼年"),
    ("CustomName", "自定义名称"),
    ("CustomNameVisible", "名称常显"),
    ("Health", "生命值"),
    ("Invulnerable", "无敌"),
    ("NoAI", "禁用 AI"),
    ("NoGravity", "无重力"),
    ("Silent", "静音"),
    ("Glowing", "发光"),
    ("Fire", "着火时间"),
    ("PortalCooldown", "传送冷却"),
    ("Rotation", "朝向"),
    ("Motion", "移动速度"),
    ("Pos", "坐标"),
    ("FallDistance", "下落距离"),
    ("Air", "氧气值"),
    ("Tags", "标签"),
    ("PersistenceRequired", "禁止自然消失"),
    ("HandItems", "手持物品"),
    ("ArmorItems", "盔甲物品"),
    ("HandDropChances", "手持掉落率"),
    ("ArmorDropChances", "盔甲掉落率"),
    ("CanPickUpLoot", "可拾取物品"),
    ("DeathLootTable", "死亡战利品表"),
    ("ActiveEffects", "状态效果"),
    ("Owner", "主人"),
    ("Sitting", "坐下"),
    ("Tame", "已驯服"),
    ("CollarColor", "项圈颜色"),
    ("Variant", "变种"),
    ("Size", "体型"),
    ("Sheared", "已剪毛"),
    ("AngryAt", "愤怒目标"),
    ("ExplosionRadius", "爆炸半径"),
    ("Fuse", "引信时间"),
    ("powered", "已充能"),
    ("ignited", "已点燃"),
    ("TileX", "方块 X 坐标"),
    ("TileY", "方块 Y 坐标"),
    ("TileZ", "方块 Z 坐标"),
    ("SpawnCount", "生成数量"),
    ("SpawnRange", "生成范围"),
    ("RequiredPlayerRange", "所需玩家距离"),
    ("MaxNearbyEntities", "附近实体上限"),
    ("Delay", "生成延迟"),
    ("MinSpawnDelay", "最短生成间隔"),
    ("MaxSpawnDelay", "最长生成间隔"),
    // ── 容器内容物里的物品堆 ──
    ("id", "类型 ID"),
    ("Count", "数量"),
    ("Slot", "槽位"),
    ("tag", "物品附加数据"),
    ("Level", "等级"),
    ("Type", "类型"),
    ("Duration", "持续时间"),
];
