//! 物品注册表。
//!
//! 带规律的条目（16 色染色、6 种材质的工具/盔甲、刷怪蛋……）不手写，
//! 而是由「基础名 × 变体」在首次访问时展开生成，避免维护上千行近似字符串。

use std::sync::OnceLock;

use super::DYE_COLORS;

/// 会被 16 色染色的物品后缀（`white_wool`、`light_blue_dye` ……）
const COLORED_SUFFIXES: &[&str] = &[
    "banner",
    "bed",
    "bundle",
    "candle",
    "carpet",
    "concrete",
    "concrete_powder",
    "dye",
    "glazed_terracotta",
    "harness",
    "shulker_box",
    "stained_glass",
    "stained_glass_pane",
    "terracotta",
    "wool",
];

/// 工具材质
const TOOL_MATERIALS: &[&str] = &["wooden", "stone", "iron", "golden", "diamond", "netherite"];

/// 工具种类
const TOOL_KINDS: &[&str] = &["sword", "pickaxe", "axe", "shovel", "hoe"];

/// 盔甲材质
const ARMOR_MATERIALS: &[&str] =
    &["leather", "chainmail", "iron", "golden", "diamond", "netherite"];

/// 盔甲部件
const ARMOR_SLOTS: &[&str] = &["helmet", "chestplate", "leggings", "boots"];

/// 马铠材质
const HORSE_ARMOR_MATERIALS: &[&str] = &["leather", "iron", "golden", "diamond", "netherite"];

/// 能生成刷怪蛋的生物
const SPAWN_EGG_MOBS: &[&str] = &[
    "allay",
    "armadillo",
    "axolotl",
    "bat",
    "bee",
    "blaze",
    "bogged",
    "breeze",
    "camel",
    "cat",
    "cave_spider",
    "chicken",
    "cod",
    "copper_golem",
    "cow",
    "creaking",
    "creeper",
    "dolphin",
    "donkey",
    "drowned",
    "elder_guardian",
    "ender_dragon",
    "enderman",
    "endermite",
    "evoker",
    "fox",
    "frog",
    "ghast",
    "glow_squid",
    "goat",
    "guardian",
    "happy_ghast",
    "hoglin",
    "horse",
    "husk",
    "iron_golem",
    "llama",
    "magma_cube",
    "mooshroom",
    "mule",
    "ocelot",
    "panda",
    "parrot",
    "phantom",
    "pig",
    "piglin",
    "piglin_brute",
    "pillager",
    "polar_bear",
    "pufferfish",
    "rabbit",
    "ravager",
    "salmon",
    "sheep",
    "shulker",
    "silverfish",
    "skeleton",
    "skeleton_horse",
    "slime",
    "sniffer",
    "snow_golem",
    "spider",
    "squid",
    "stray",
    "strider",
    "tadpole",
    "trader_llama",
    "tropical_fish",
    "turtle",
    "vex",
    "villager",
    "vindicator",
    "wandering_trader",
    "warden",
    "witch",
    "wither",
    "wither_skeleton",
    "wolf",
    "zoglin",
    "zombie",
    "zombie_horse",
    "zombie_villager",
    "zombified_piglin",
];

/// 不区分颜色/材质的基础物品
const BASE_ITEMS: &[&str] = &[
    // ── 材料与矿物 ──
    "amethyst_shard",
    "blaze_powder",
    "blaze_rod",
    "bone",
    "bone_meal",
    "book",
    "breeze_rod",
    "brick",
    "charcoal",
    "clay_ball",
    "coal",
    "copper_ingot",
    "copper_nugget",
    "diamond",
    "disc_fragment_5",
    "dragon_breath",
    "echo_shard",
    "emerald",
    "ender_eye",
    "ender_pearl",
    "experience_bottle",
    "eye_of_ender",
    "feather",
    "fermented_spider_eye",
    "fire_charge",
    "flint",
    "ghast_tear",
    "glow_ink_sac",
    "glowstone_dust",
    "gold_ingot",
    "gold_nugget",
    "gunpowder",
    "heart_of_the_sea",
    "heavy_core",
    "honeycomb",
    "ink_sac",
    "iron_ingot",
    "iron_nugget",
    "lapis_lazuli",
    "leather",
    "magma_cream",
    "nautilus_shell",
    "nether_star",
    "netherite_ingot",
    "netherite_scrap",
    "phantom_membrane",
    "prismarine_crystals",
    "prismarine_shard",
    "quartz",
    "rabbit_foot",
    "rabbit_hide",
    "raw_copper",
    "raw_gold",
    "raw_iron",
    "redstone",
    "resin_block",
    "resin_brick",
    "resin_clump",
    "shulker_shell",
    "slime_ball",
    "stick",
    "string",
    "turtle_scute",
    "wind_charge",
    // ── 食物 ──
    "apple",
    "baked_potato",
    "beef",
    "beetroot",
    "beetroot_soup",
    "bread",
    "cake",
    "carrot",
    "chicken",
    "chorus_fruit",
    "cod",
    "cooked_beef",
    "cooked_chicken",
    "cooked_cod",
    "cooked_mutton",
    "cooked_porkchop",
    "cooked_rabbit",
    "cooked_salmon",
    "cookie",
    "dried_kelp",
    "enchanted_golden_apple",
    "glow_berries",
    "golden_apple",
    "golden_carrot",
    "honey_bottle",
    "melon_slice",
    "mushroom_stew",
    "mutton",
    "poisonous_potato",
    "popped_chorus_fruit",
    "porkchop",
    "potato",
    "pufferfish",
    "pumpkin_pie",
    "rabbit",
    "rabbit_stew",
    "rotten_flesh",
    "salmon",
    "spider_eye",
    "suspicious_stew",
    "sweet_berries",
    "tropical_fish",
    "dried_kelp_block",
    // ── 农业 ──
    "bamboo",
    "beetroot_seeds",
    "cocoa_beans",
    "hay_block",
    "kelp",
    "melon_seeds",
    "nether_wart",
    "pitcher_pod",
    "pumpkin_seeds",
    "sugar",
    "sugar_cane",
    "torchflower_seeds",
    "wheat",
    "wheat_seeds",
    // ── 桶 ──
    "axolotl_bucket",
    "bucket",
    "cod_bucket",
    "lava_bucket",
    "milk_bucket",
    "powder_snow_bucket",
    "pufferfish_bucket",
    "salmon_bucket",
    "tadpole_bucket",
    "tropical_fish_bucket",
    "water_bucket",
    // ── 药水与投掷物 ──
    "arrow",
    "firework_rocket",
    "firework_star",
    "lingering_potion",
    "ominous_bottle",
    "potion",
    "spectral_arrow",
    "splash_potion",
    "tipped_arrow",
    // ── 装备与工具 ──
    "bow",
    "brush",
    "carrot_on_a_stick",
    "crossbow",
    "elytra",
    "fishing_rod",
    "flint_and_steel",
    "lead",
    "mace",
    "shears",
    "shield",
    "spyglass",
    "totem_of_undying",
    "trident",
    "turtle_helmet",
    "warped_fungus_on_a_stick",
    "wolf_armor",
    // ── 红石与功能方块 ──
    "calibrated_sculk_sensor",
    "comparator",
    "crafter",
    "daylight_detector",
    "dispenser",
    "dropper",
    "hopper",
    "lever",
    "lightning_rod",
    "observer",
    "piston",
    "redstone_lamp",
    "redstone_torch",
    "repeater",
    "sculk_sensor",
    "sculk_shrieker",
    "sticky_piston",
    "target",
    "tripwire_hook",
    // ── 容器与工作站 ──
    "anvil",
    "barrel",
    "beacon",
    "bell",
    "blast_furnace",
    "brewing_stand",
    "campfire",
    "cartography_table",
    "cauldron",
    "chest",
    "chipped_anvil",
    "composter",
    "conduit",
    "crafting_table",
    "damaged_anvil",
    "decorated_pot",
    "enchanting_table",
    "ender_chest",
    "end_crystal",
    "end_portal_frame",
    "end_rod",
    "fletching_table",
    "flower_pot",
    "furnace",
    "grindstone",
    "iron_bars",
    "item_frame",
    "glow_item_frame",
    "jukebox",
    "ladder",
    "lantern",
    "soul_lantern",
    "lectern",
    "lodestone",
    "loom",
    "note_block",
    "painting",
    "scaffolding",
    "smithing_table",
    "smoker",
    "soul_campfire",
    "stonecutter",
    "torch",
    "soul_torch",
    "trapped_chest",
    // ── 唱片 ──
    "music_disc_11",
    "music_disc_13",
    "music_disc_blocks",
    "music_disc_cat",
    "music_disc_chirp",
    "music_disc_creator",
    "music_disc_creator_music_box",
    "music_disc_far",
    "music_disc_lava_chicken",
    "music_disc_mall",
    "music_disc_mellohi",
    "music_disc_otherside",
    "music_disc_pigstep",
    "music_disc_precipice",
    "music_disc_relic",
    "music_disc_stal",
    "music_disc_strad",
    "music_disc_wait",
    "music_disc_ward",
    // ── 生物头颅 ──
    "creeper_head",
    "dragon_head",
    "piglin_head",
    "player_head",
    "skeleton_skull",
    "wither_skeleton_skull",
    "zombie_head",
    // ── 陶片 ──
    "angler_pottery_sherd",
    "archer_pottery_sherd",
    "arms_up_pottery_sherd",
    "blade_pottery_sherd",
    "brewer_pottery_sherd",
    "burn_pottery_sherd",
    "danger_pottery_sherd",
    "explorer_pottery_sherd",
    "flow_pottery_sherd",
    "friend_pottery_sherd",
    "guster_pottery_sherd",
    "heart_pottery_sherd",
    "heartbreak_pottery_sherd",
    "howl_pottery_sherd",
    "miner_pottery_sherd",
    "mourner_pottery_sherd",
    "plenty_pottery_sherd",
    "prize_pottery_sherd",
    "scrape_pottery_sherd",
    "sheaf_pottery_sherd",
    "shelter_pottery_sherd",
    "skull_pottery_sherd",
    "snort_pottery_sherd",
    // ── 旗帜图案 ──
    "bordure_indented_banner_pattern",
    "creeper_banner_pattern",
    "field_masoned_banner_pattern",
    "flow_banner_pattern",
    "flower_banner_pattern",
    "globe_banner_pattern",
    "guster_banner_pattern",
    "mojang_banner_pattern",
    "piglin_banner_pattern",
    "skull_banner_pattern",
    "thing_banner_pattern",
    // ── 盔甲纹饰模板 ──
    "bolt_armor_trim_smithing_template",
    "coast_armor_trim_smithing_template",
    "dune_armor_trim_smithing_template",
    "eye_armor_trim_smithing_template",
    "flow_armor_trim_smithing_template",
    "host_armor_trim_smithing_template",
    "netherite_upgrade_smithing_template",
    "raiser_armor_trim_smithing_template",
    "rib_armor_trim_smithing_template",
    "sentry_armor_trim_smithing_template",
    "shaper_armor_trim_smithing_template",
    "silence_armor_trim_smithing_template",
    "snout_armor_trim_smithing_template",
    "spire_armor_trim_smithing_template",
    "tide_armor_trim_smithing_template",
    "vex_armor_trim_smithing_template",
    "ward_armor_trim_smithing_template",
    "wayfinder_armor_trim_smithing_template",
    "wild_armor_trim_smithing_template",
    // ── 其它 ──
    "armor_stand",
    "barrier",
    "command_block",
    "chain_command_block",
    "repeating_command_block",
    "debug_stick",
    "knowledge_book",
    "netherite_upgrade_smithing_template",
    "ominous_trial_key",
    "saddle",
    "structure_block",
    "structure_void",
    "trial_key",
    "writable_book",
    "written_book",
];

static ITEMS: OnceLock<Vec<&'static str>> = OnceLock::new();

/// 生成后的完整物品表（进程内只算一次）
pub(crate) fn base_items() -> &'static [&'static str] {
    ITEMS.get_or_init(|| {
        let mut v: Vec<&'static str> = BASE_ITEMS.to_vec();

        for color in DYE_COLORS {
            for suffix in COLORED_SUFFIXES {
                v.push(intern(format!("{color}_{suffix}")));
            }
        }
        for material in TOOL_MATERIALS {
            for kind in TOOL_KINDS {
                v.push(intern(format!("{material}_{kind}")));
            }
        }
        for material in ARMOR_MATERIALS {
            for slot in ARMOR_SLOTS {
                v.push(intern(format!("{material}_{slot}")));
            }
        }
        for material in HORSE_ARMOR_MATERIALS {
            v.push(intern(format!("{material}_horse_armor")));
        }
        for mob in SPAWN_EGG_MOBS {
            v.push(intern(format!("{mob}_spawn_egg")));
        }

        v.sort_unstable();
        v.dedup();
        v
    })
}

/// 把拼出来的字符串提升为 `'static`。
///
/// 只在首次访问注册表时调用一次，总量也就几百条短字符串，
/// 相对于一次性的堆占用（而非持续泄漏）是可以接受的。
fn intern(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}
