//! 把指令里的英文 ID / 关键字翻成中文，供执行反馈展示。
//!
//! 不追求逐条罗列上万个名字，而是「词典 + 按 `_` 贪心合并相邻词」：
//! `light_blue_wool` 会先匹配 `light_blue`（淡蓝色）再匹配 `wool`（羊毛），
//! 拼成「淡蓝色羊毛」。认不出来的词原样保留，不会凭空丢信息。

use std::collections::HashMap;
use std::sync::OnceLock;

/// 目标选择器
const SELECTORS: &[(&str, &str)] = &[
    ("@a", "所有玩家"),
    ("@e", "所有实体"),
    ("@p", "最近的玩家"),
    ("@r", "随机玩家"),
    ("@s", "指令执行者"),
    ("@n", "最近的实体"),
    ("@c", "指令执行者"),
    ("@v", "指令执行者"),
    ("@i", "指令执行者"),
];

/// 一个 ID 最多合并几段词（`eye_of_ender` 是 3 段）
const MAX_PARTS: usize = 4;

/// 词典。既收单段词（`sword`），也收组合词（`light_blue`、`stone_bricks`），
/// 匹配时优先尝试更长的组合。
const DICT: &[(&str, &str)] = &[
    // ── 游戏模式 ──
    ("survival", "生存模式"),
    ("creative", "创造模式"),
    ("adventure", "冒险模式"),
    ("spectator", "旁观模式"),
    // ── 难度 ──
    ("peaceful", "和平"),
    ("easy", "简单"),
    ("normal", "普通"),
    ("hard", "困难"),
    // ── 天气与时间 ──
    ("clear", "晴天"),
    ("rain", "雨天"),
    ("thunder", "雷暴"),
    ("day", "白天"),
    ("night", "夜晚"),
    ("noon", "正午"),
    ("midnight", "午夜"),
    ("sunrise", "日出"),
    ("sunset", "日落"),
    ("daytime", "白天时长"),
    ("gametime", "游戏时间"),
    // ── 布尔 ──
    ("true", "开启"),
    ("false", "关闭"),
    // ── 16 种颜色 ──
    ("white", "白色"),
    ("orange", "橙色"),
    ("magenta", "品红色"),
    ("light_blue", "淡蓝色"),
    ("yellow", "黄色"),
    ("lime", "黄绿色"),
    ("pink", "粉红色"),
    ("gray", "灰色"),
    ("light_gray", "淡灰色"),
    ("cyan", "青色"),
    ("purple", "紫色"),
    ("blue", "蓝色"),
    ("brown", "棕色"),
    ("green", "绿色"),
    ("red", "红色"),
    ("black", "黑色"),
    // ── 木种与菌类 ──
    ("oak", "橡木"),
    ("spruce", "云杉木"),
    ("birch", "白桦木"),
    ("jungle", "丛林木"),
    ("acacia", "金合欢木"),
    ("dark_oak", "深色橡木"),
    ("mangrove", "红树木"),
    ("cherry", "樱花木"),
    ("pale_oak", "苍白橡木"),
    ("bamboo", "竹"),
    ("crimson", "绯红"),
    ("warped", "诡异"),
    ("crimson_stem", "绯红菌柄"),
    ("warped_stem", "诡异菌柄"),
    // ── 材质 ──
    ("wooden", "木"),
    ("leather", "皮革"),
    ("chainmail", "锁链"),
    ("golden", "金"),
    ("iron", "铁"),
    ("diamond", "钻石"),
    ("netherite", "下界合金"),
    ("copper", "铜"),
    ("emerald", "绿宝石"),
    ("lapis", "青金石"),
    ("amethyst", "紫水晶"),
    ("quartz", "石英"),
    ("lapis_lazuli", "青金石"),
    // ── 工具与武器 ──
    ("sword", "剑"),
    ("pickaxe", "镐"),
    ("shovel", "锹"),
    ("axe", "斧"),
    ("hoe", "锄"),
    ("bow", "弓"),
    ("crossbow", "弩"),
    ("arrow", "箭"),
    ("spectral_arrow", "光灵箭"),
    ("tipped_arrow", "药箭"),
    ("trident", "三叉戟"),
    ("mace", "重锤"),
    ("shield", "盾牌"),
    ("shears", "剪刀"),
    ("brush", "刷子"),
    ("spyglass", "望远镜"),
    ("fishing_rod", "钓鱼竿"),
    ("flint_and_steel", "打火石"),
    ("carrot_on_a_stick", "胡萝卜钓竿"),
    // ── 护甲 ──
    ("helmet", "头盔"),
    ("chestplate", "胸甲"),
    ("leggings", "护腿"),
    ("boots", "靴子"),
    ("horse_armor", "马铠"),
    ("turtle_helmet", "海龟壳"),
    ("wolf_armor", "狼铠"),
    // ── 着色物与建材后缀 ──
    ("wool", "羊毛"),
    ("carpet", "地毯"),
    ("concrete", "混凝土"),
    ("concrete_powder", "混凝土粉末"),
    ("terracotta", "陶瓦"),
    ("glazed_terracotta", "带釉陶瓦"),
    ("stained_glass", "染色玻璃"),
    ("stained_glass_pane", "染色玻璃板"),
    ("shulker_box", "潜影盒"),
    ("bed", "床"),
    ("banner", "旗帜"),
    ("banner_pattern", "旗帜图案"),
    ("candle", "蜡烛"),
    ("dye", "染料"),
    ("bundle", "收纳袋"),
    ("harness", "挽具"),
    ("planks", "木板"),
    ("mosaic", "镶嵌板"),
    ("log", "原木"),
    ("wood", "木头"),
    ("hyphae", "菌核"),
    ("stripped", "去皮"),
    ("sapling", "树苗"),
    ("leaves", "树叶"),
    ("door", "门"),
    ("trapdoor", "活板门"),
    ("fence_gate", "栅栏门"),
    ("fence", "栅栏"),
    ("button", "按钮"),
    ("pressure_plate", "压力板"),
    ("slab", "台阶"),
    ("stairs", "楼梯"),
    ("hanging_sign", "悬挂式告示牌"),
    ("sign", "告示牌"),
    ("chest_boat", "运输船"),
    ("boat", "船"),
    ("wall", "墙"),
    ("pane", "板"),
    ("grate", "格栅"),
    ("bulb", "灯泡"),
    ("chain", "锁链"),
    ("bars", "栏杆"),
    ("slime_block", "黏液块"),
    ("honey_block", "蜂蜜块"),
    // ── 石料 ──
    ("stone_bricks", "石砖"),
    ("stone_brick", "石砖"),
    ("stone", "石头"),
    ("cobblestone", "圆石"),
    ("deepslate", "深板岩"),
    ("cobbled_deepslate", "深板岩圆石"),
    ("blackstone", "黑石"),
    ("basalt", "玄武岩"),
    ("tuff", "凝灰岩"),
    ("calcite", "方解石"),
    ("dripstone", "滴水石"),
    ("granite", "花岗岩"),
    ("diorite", "闪长岩"),
    ("andesite", "安山岩"),
    ("sandstone", "砂岩"),
    ("red_sandstone", "红砂岩"),
    ("prismarine", "海晶石"),
    ("purpur", "紫珀"),
    ("end_stone", "末地石"),
    ("netherrack", "下界岩"),
    ("nether_bricks", "下界砖"),
    ("nether_brick", "下界砖"),
    ("bricks", "砖块"),
    ("brick", "砖"),
    ("mud_bricks", "泥砖"),
    ("mud_brick", "泥砖"),
    ("resin_bricks", "树脂砖"),
    ("resin_brick", "树脂砖"),
    ("mossy", "苔藓"),
    ("cracked", "裂纹"),
    ("chiseled", "雕纹"),
    ("polished", "磨制"),
    ("smooth", "平滑"),
    ("cut", "切制"),
    ("tiles", "瓦"),
    ("blocks", "块"),
    ("block", "块"),
    ("ore", "矿石"),
    ("raw", "粗"),
    ("waxed", "打蜡"),
    ("exposed", "斑驳"),
    ("weathered", "风化"),
    ("oxidized", "氧化"),
    ("mud", "泥"),
    ("clay", "黏土"),
    ("dirt", "泥土"),
    ("grass", "草"),
    ("sand", "沙子"),
    ("red_sand", "红沙"),
    ("gravel", "沙砾"),
    ("glass", "玻璃"),
    ("ice", "冰"),
    ("snow", "雪"),
    ("packed_ice", "浮冰"),
    ("blue_ice", "蓝冰"),
    ("obsidian", "黑曜石"),
    ("bedrock", "基岩"),
    ("crying_obsidian", "哭泣的黑曜石"),
    ("soul_sand", "灵魂沙"),
    ("soul_soil", "灵魂土"),
    ("soul", "灵魂"),
    ("magma", "岩浆"),
    ("lava", "岩浆"),
    ("water", "水"),
    ("glowstone", "荧石"),
    ("sea_lantern", "海晶灯"),
    ("shroomlight", "菌光体"),
    ("froglight", "蛙明灯"),
    ("lantern", "灯笼"),
    ("torch", "火把"),
    ("campfire", "营火"),
    ("fire", "火"),
    ("nether", "下界"),
    ("end", "末地"),
    ("ender", "末影"),
    ("sculk", "幽匿"),
    ("amethyst_cluster", "紫水晶簇"),
    ("budding_amethyst", "紫水晶母岩"),
    ("chorus", "紫颂"),
    ("sponge", "海绵"),
    ("cobweb", "蜘蛛网"),
    ("vine", "藤蔓"),
    ("cactus", "仙人掌"),
    ("melon", "西瓜"),
    ("pumpkin", "南瓜"),
    ("hay", "干草"),
    ("bone", "骨"),
    ("kelp", "海带"),
    ("dried_kelp", "干海带"),
    ("sea_pickle", "海泡菜"),
    ("spore_blossom", "孢子花"),
    ("azalea", "杜鹃"),
    ("moss", "苔藓"),
    ("fern", "蕨"),
    ("poppy", "虞美人"),
    ("dandelion", "蒲公英"),
    ("torchflower", "火把花"),
    ("pitcher", "瓶子草"),
    ("rose", "玫瑰"),
    ("wither_rose", "凋灵玫瑰"),
    ("sunflower", "向日葵"),
    ("lilac", "丁香"),
    ("tulip", "郁金香"),
    ("orchid", "兰花"),
    ("allium", "绒球葱"),
    ("bluet", "蓝花美耳草"),
    ("daisy", "雏菊"),
    ("cornflower", "矢车菊"),
    ("lily", "睡莲"),
    ("sapling", "树苗"),
    // ── 功能方块 ──
    ("chest", "箱子"),
    ("ender_chest", "末影箱"),
    ("trapped_chest", "陷阱箱"),
    ("barrel", "木桶"),
    ("furnace", "熔炉"),
    ("smoker", "烟熏炉"),
    ("blast_furnace", "高炉"),
    ("crafting_table", "工作台"),
    ("anvil", "铁砧"),
    ("chipped_anvil", "开裂的铁砧"),
    ("damaged_anvil", "损坏的铁砧"),
    ("hopper", "漏斗"),
    ("dropper", "投掷器"),
    ("dispenser", "发射器"),
    ("observer", "侦测器"),
    ("sticky_piston", "黏性活塞"),
    ("piston", "活塞"),
    ("tnt", "TNT"),
    ("ladder", "梯子"),
    ("scaffolding", "脚手架"),
    ("powered_rail", "充能铁轨"),
    ("detector_rail", "探测铁轨"),
    ("activator_rail", "激活铁轨"),
    ("rail", "铁轨"),
    ("bookshelf", "书架"),
    ("chiseled_bookshelf", "雕纹书架"),
    ("lectern", "讲台"),
    ("loom", "织布机"),
    ("grindstone", "砂轮"),
    ("stonecutter", "切石机"),
    ("smithing_table", "锻造台"),
    ("fletching_table", "制箭台"),
    ("cartography_table", "制图台"),
    ("composter", "堆肥桶"),
    ("cauldron", "炼药锅"),
    ("brewing_stand", "酿造台"),
    ("enchanting_table", "附魔台"),
    ("beacon", "信标"),
    ("conduit", "潮涌核心"),
    ("respawn_anchor", "重生锚"),
    ("lodestone", "磁石"),
    ("bell", "钟"),
    ("jukebox", "唱片机"),
    ("note_block", "音符盒"),
    ("target", "标靶"),
    ("tripwire_hook", "绊线钩"),
    ("lever", "拉杆"),
    ("repeater", "红石中继器"),
    ("comparator", "红石比较器"),
    ("redstone_lamp", "红石灯"),
    ("daylight_detector", "阳光探测器"),
    ("lightning_rod", "避雷针"),
    ("flower_pot", "花盆"),
    ("decorated_pot", "饰纹陶罐"),
    ("armor_stand", "盔甲架"),
    ("item_frame", "物品展示框"),
    ("glow_item_frame", "荧光物品展示框"),
    ("painting", "画"),
    ("structure_block", "结构方块"),
    ("command_block", "命令方块"),
    ("chain_command_block", "连锁型命令方块"),
    ("repeating_command_block", "循环型命令方块"),
    ("barrier", "屏障"),
    ("light", "光源方块"),
    ("sculk_catalyst", "幽匿催发体"),
    ("sculk_sensor", "幽匿感测体"),
    ("sculk_shrieker", "幽匿尖啸体"),
    ("sculk_vein", "幽匿脉络"),
    ("vault", "试炼密室宝库"),
    ("trial_spawner", "试炼刷怪笼"),
    ("spawner", "刷怪笼"),
    ("bee_nest", "蜂巢"),
    ("beehive", "蜂箱"),
    ("honeycomb", "蜜脾"),
    ("honey", "蜂蜜"),
    ("creaking_heart", "嘎枝之心"),
    ("heavy_core", "沉重核心"),
    // ── 材料 ──
    ("ingot", "锭"),
    ("nugget", "粒"),
    ("scrap", "碎片"),
    ("shard", "碎片"),
    ("rod", "棒"),
    ("powder", "粉"),
    ("dust", "粉"),
    ("ball", "球"),
    ("hide", "皮"),
    ("scute", "鳞甲"),
    ("shell", "壳"),
    ("crystal", "水晶"),
    ("pearl", "珍珠"),
    ("tear", "之泪"),
    ("membrane", "膜"),
    ("string", "线"),
    ("feather", "羽毛"),
    ("flint", "燧石"),
    ("paper", "纸"),
    ("book", "书"),
    ("writable_book", "书与笔"),
    ("written_book", "成书"),
    ("enchanted_book", "附魔书"),
    ("knowledge_book", "知识之书"),
    ("name_tag", "命名牌"),
    ("saddle", "鞍"),
    ("elytra", "鞘翅"),
    ("totem_of_undying", "不死图腾"),
    ("experience_bottle", "附魔之瓶"),
    ("ominous_bottle", "不祥之瓶"),
    ("ender_pearl", "末影珍珠"),
    ("eye_of_ender", "末影之眼"),
    ("ender_eye", "末影之眼"),
    ("ender_crystal", "末影水晶"),
    ("fire_charge", "火焰弹"),
    ("firework_rocket", "烟花火箭"),
    ("firework_star", "烟火之星"),
    ("gunpowder", "火药"),
    ("blaze_rod", "烈焰棒"),
    ("blaze_powder", "烈焰粉"),
    ("ghast_tear", "恶魂之泪"),
    ("magma_cream", "岩浆膏"),
    ("slime_ball", "黏液球"),
    ("nether_star", "下界之星"),
    ("dragon_breath", "龙息"),
    ("dragon_egg", "龙蛋"),
    ("echo_shard", "回响碎片"),
    ("disc_fragment_5", "唱片残片 5"),
    ("breeze_rod", "旋风棒"),
    ("wind_charge", "风弹"),
    ("resin", "树脂"),
    ("resin_clump", "树脂团"),
    ("nautilus_shell", "鹦鹉螺壳"),
    ("heart_of_the_sea", "海洋之心"),
    ("prismarine_crystals", "海晶砂粒"),
    ("prismarine_shard", "海晶碎片"),
    ("phantom_membrane", "幻翼膜"),
    ("rabbit_hide", "兔子皮"),
    ("rabbit_foot", "兔子脚"),
    ("coal", "煤炭"),
    ("charcoal", "木炭"),
    ("stick", "木棍"),
    ("bowl", "碗"),
    ("bucket", "桶"),
    ("bottle", "瓶"),
    ("clay_ball", "黏土球"),
    ("slime", "黏液"),
    ("leather", "皮革"),
    ("brick", "砖"),
    ("nether_wart", "下界疣"),
    ("sugar", "糖"),
    ("sugar_cane", "甘蔗"),
    ("cocoa_beans", "可可豆"),
    ("wheat", "小麦"),
    ("seeds", "种子"),
    ("bone_meal", "骨粉"),
    ("ink_sac", "墨囊"),
    ("glow_ink_sac", "荧光墨囊"),
    ("egg", "鸡蛋"),
    ("feather", "羽毛"),
    // ── 食物 ──
    ("apple", "苹果"),
    ("golden_apple", "金苹果"),
    ("enchanted_golden_apple", "附魔金苹果"),
    ("bread", "面包"),
    ("cookie", "曲奇"),
    ("cake", "蛋糕"),
    ("beef", "牛肉"),
    ("porkchop", "猪排"),
    ("chicken", "鸡肉"),
    ("mutton", "羊肉"),
    ("rabbit", "兔肉"),
    ("cod", "鳕鱼"),
    ("salmon", "鲑鱼"),
    ("tropical_fish", "热带鱼"),
    ("pufferfish", "河豚"),
    ("cooked", "熟"),
    ("carrot", "胡萝卜"),
    ("potato", "马铃薯"),
    ("baked_potato", "烤马铃薯"),
    ("poisonous_potato", "毒马铃薯"),
    ("beetroot", "甜菜根"),
    ("soup", "汤"),
    ("stew", "煲"),
    ("mushroom_stew", "蘑菇煲"),
    ("rabbit_stew", "兔肉煲"),
    ("beetroot_soup", "甜菜汤"),
    ("suspicious_stew", "谜之炖菜"),
    ("pumpkin_pie", "南瓜派"),
    ("melon_slice", "西瓜片"),
    ("berries", "浆果"),
    ("glow_berries", "荧光浆果"),
    ("sweet_berries", "甜浆果"),
    ("chorus_fruit", "紫颂果"),
    ("popped_chorus_fruit", "爆裂紫颂果"),
    ("rotten_flesh", "腐肉"),
    ("spider_eye", "蜘蛛眼"),
    ("fermented_spider_eye", "发酵蛛眼"),
    ("honey_bottle", "蜂蜜瓶"),
    ("milk_bucket", "奶桶"),
    ("water_bucket", "水桶"),
    ("lava_bucket", "岩浆桶"),
    ("powder_snow_bucket", "细雪桶"),
    ("axolotl_bucket", "美西螈桶"),
    ("cod_bucket", "鳕鱼桶"),
    ("salmon_bucket", "鲑鱼桶"),
    ("pufferfish_bucket", "河豚桶"),
    ("tropical_fish_bucket", "热带鱼桶"),
    ("tadpole_bucket", "蝌蚪桶"),
    ("suspicious", "谜之"),
    // ── 药水与效果 ──
    ("potion", "药水"),
    ("splash_potion", "喷溅型药水"),
    ("lingering_potion", "滞留型药水"),
    ("speed", "迅捷"),
    ("slowness", "缓慢"),
    ("haste", "急迫"),
    ("mining_fatigue", "挖掘疲劳"),
    ("strength", "力量"),
    ("instant_health", "瞬间治疗"),
    ("instant_damage", "瞬间伤害"),
    ("jump_boost", "跳跃提升"),
    ("nausea", "反胃"),
    ("regeneration", "生命恢复"),
    ("resistance", "抗性提升"),
    ("fire_resistance", "抗火"),
    ("water_breathing", "水下呼吸"),
    ("invisibility", "隐身"),
    ("blindness", "失明"),
    ("night_vision", "夜视"),
    ("hunger", "饥饿"),
    ("weakness", "虚弱"),
    ("poison", "中毒"),
    ("wither", "凋零"),
    ("health_boost", "生命提升"),
    ("absorption", "伤害吸收"),
    ("saturation", "饱和"),
    ("glowing", "发光"),
    ("levitation", "飘浮"),
    ("luck", "幸运"),
    ("unluck", "霉运"),
    ("slow_falling", "缓降"),
    ("conduit_power", "潮涌能量"),
    ("dolphins_grace", "海豚的恩惠"),
    ("bad_omen", "不祥之兆"),
    ("hero_of_the_village", "村庄英雄"),
    ("darkness", "黑暗"),
    ("trial_omen", "试炼之兆"),
    ("raid_omen", "袭击之兆"),
    ("wind_charged", "蓄风"),
    ("weaving", "盘丝"),
    ("oozing", "渗浆"),
    ("infested", "寄生"),
    // ── 附魔 ──
    ("sharpness", "锋利"),
    ("smite", "亡灵杀手"),
    ("bane_of_arthropods", "节肢杀手"),
    ("knockback", "击退"),
    ("fire_aspect", "火焰附加"),
    ("looting", "抢夺"),
    ("sweeping_edge", "横扫之刃"),
    ("efficiency", "效率"),
    ("silk_touch", "精准采集"),
    ("unbreaking", "耐久"),
    ("fortune", "时运"),
    ("power", "力量"),
    ("punch", "冲击"),
    ("flame", "火焰"),
    ("infinity", "无限"),
    ("luck_of_the_sea", "海之眷顾"),
    ("lure", "饵钓"),
    ("loyalty", "忠诚"),
    ("impaling", "穿刺"),
    ("riptide", "激流"),
    ("channeling", "引雷"),
    ("multishot", "多重射击"),
    ("quick_charge", "快速装填"),
    ("piercing", "穿透"),
    ("density", "致密"),
    ("breach", "破甲"),
    ("wind_burst", "风爆"),
    ("mending", "经验修补"),
    ("vanishing_curse", "消失诅咒"),
    ("binding_curse", "绑定诅咒"),
    ("protection", "保护"),
    ("fire_protection", "火焰保护"),
    ("feather_falling", "摔落保护"),
    ("blast_protection", "爆炸保护"),
    ("projectile_protection", "弹射物保护"),
    ("respiration", "水下呼吸"),
    ("aqua_affinity", "水下速掘"),
    ("thorns", "荆棘"),
    ("depth_strider", "深海探索者"),
    ("frost_walker", "冰霜行者"),
    ("soul_speed", "灵魂疾行"),
    ("swift_sneak", "迅捷潜行"),
    // ── 伤害类型 ──
    ("fall", "摔落"),
    ("falling", "下落"),
    ("drowning", "溺水"),
    ("explosion", "爆炸"),
    ("magic", "魔法"),
    ("mob_attack", "生物攻击"),
    ("player_attack", "玩家攻击"),
    ("player_explosion", "玩家爆炸"),
    ("sonic_boom", "音波尖啸"),
    ("starve", "饥饿"),
    ("freeze", "冰冻"),
    ("lightning", "闪电"),
    ("cramming", "过度拥挤"),
    ("hot_floor", "热地板"),
    ("in_wall", "墙内窒息"),
    ("out_of_world", "世界之外"),
    ("outside_border", "世界边界外"),
    ("cactus", "仙人掌"),
    ("void", "虚空"),
    ("in_fire", "着火"),
    ("on_fire", "火焰灼烧"),
    ("thrown", "投掷物"),
    ("spit", "羊驼唾沫"),
    ("stalagmite", "石笋"),
    ("stinger", "蜂蜇"),
    ("sweet_berry_bush", "甜浆果丛"),
    ("generic", "通用"),
    ("bad_respawn_point", "错误的出生点"),
    ("falling_anvil", "下落的铁砧"),
    ("falling_block", "下落的方块"),
    ("falling_stalactite", "下落的钟乳石"),
    ("fireworks", "烟花"),
    ("fly_into_wall", "撞击墙壁"),
    ("unattributed_fireball", "无名火球"),
    ("dry_out", "干燥"),
    ("dragon_breath", "龙息"),
    // ── 实体属性（ID 用 `.` 分隔，按整条匹配） ──
    ("generic.max_health", "最大生命值"),
    ("generic.follow_range", "跟随范围"),
    ("generic.knockback_resistance", "击退抗性"),
    ("generic.movement_speed", "移动速度"),
    ("generic.flying_speed", "飞行速度"),
    ("generic.attack_damage", "攻击伤害"),
    ("generic.attack_knockback", "攻击击退"),
    ("generic.attack_speed", "攻击速度"),
    ("generic.armor", "护甲值"),
    ("generic.armor_toughness", "护甲韧性"),
    ("generic.luck", "幸运值"),
    ("generic.scale", "体型"),
    ("generic.step_height", "行走高度"),
    ("generic.gravity", "重力"),
    ("generic.jump_strength", "跳跃力度"),
    ("generic.safe_fall_distance", "安全下落距离"),
    ("generic.fall_damage_multiplier", "摔落伤害倍率"),
    ("generic.burning_time", "燃烧时间"),
    ("generic.max_absorption", "最大伤害吸收"),
    ("generic.movement_efficiency", "移动效率"),
    ("generic.oxygen_bonus", "氧气加成"),
    ("generic.water_movement_efficiency", "水中移动效率"),
    ("generic.explosion_knockback_resistance", "爆炸击退抗性"),
    ("player.block_break_speed", "方块破坏速度"),
    ("player.block_interaction_range", "方块交互距离"),
    ("player.entity_interaction_range", "实体交互距离"),
    ("player.mining_efficiency", "挖掘效率"),
    ("player.sneaking_speed", "潜行速度"),
    ("player.submerged_mining_speed", "水下挖掘速度"),
    ("player.sweeping_damage_ratio", "横扫伤害比"),
    ("zombie.spawn_reinforcements", "僵尸增援几率"),
    // ── 游戏规则 ──
    ("keepInventory", "死亡不掉落"),
    ("doDaylightCycle", "昼夜交替"),
    ("doWeatherCycle", "天气更替"),
    ("doMobSpawning", "生物生成"),
    ("doMobLoot", "生物掉落物"),
    ("doTileDrops", "方块掉落物"),
    ("doEntityDrops", "实体掉落物"),
    ("doFireTick", "火焰蔓延"),
    ("mobGriefing", "生物破坏方块"),
    ("naturalRegeneration", "自然回血"),
    ("randomTickSpeed", "随机刻速度"),
    ("commandBlockOutput", "命令方块输出"),
    ("logAdminCommands", "记录管理员指令"),
    ("sendCommandFeedback", "指令执行反馈"),
    ("showDeathMessages", "显示死亡消息"),
    ("showCoordinates", "显示坐标"),
    ("reducedDebugInfo", "精简调试信息"),
    ("spectatorsGenerateChunks", "旁观者加载区块"),
    ("announceAdvancements", "公告进度完成"),
    ("maxCommandChainLength", "指令链长度上限"),
    ("spawnRadius", "出生点半径"),
    ("spawnMonsters", "生成怪物"),
    ("doImmediateRespawn", "立即重生"),
    ("doInsomnia", "幻翼生成"),
    ("doPatrolSpawning", "巡逻队生成"),
    ("doTraderSpawning", "流浪商人生成"),
    ("doWardenSpawning", "监守者生成"),
    ("doVinesSpread", "藤蔓蔓延"),
    ("doLimitedCrafting", "限制合成"),
    ("disableRaids", "禁用袭击"),
    ("fallDamage", "摔落伤害"),
    ("fireDamage", "火焰伤害"),
    ("freezeDamage", "冰冻伤害"),
    ("drowningDamage", "溺水伤害"),
    ("playersSleepingPercentage", "入睡玩家比例"),
    ("lavaSourceConversion", "岩浆源转换"),
    ("waterSourceConversion", "水源转换"),
    ("projectilesCanBreakBlocks", "弹射物破坏方块"),
    ("forgiveDeadPlayers", "原谅死亡玩家"),
    ("universalAnger", "全体激怒"),
    ("globalSoundEvents", "全局音效事件"),
    ("snowAccumulationHeight", "积雪高度"),
    ("enderPearlsVanishOnDeath", "末影珍珠死亡消失"),
    // ── 粒子 ──
    ("angry_villager", "村民愤怒"),
    ("ambient_entity_effect", "实体状态效果"),
    ("ash", "灰烬"),
    ("bubble", "气泡"),
    ("campfire_cosy_smoke", "营火炊烟"),
    ("campfire_signal_smoke", "营火信号烟"),
    ("cloud", "云雾"),
    ("crit", "暴击"),
    ("damage_indicator", "伤害指示"),
    ("dust_color_transition", "变色尘埃"),
    ("effect", "状态效果"),
    ("elder_guardian", "远古守卫者"),
    ("enchant", "附魔"),
    ("enchanted_hit", "附魔命中"),
    ("end_rod", "末地烛"),
    ("falling_dust", "下落尘埃"),
    ("flash", "闪光"),
    ("glow", "荧光"),
    ("happy_villager", "村民高兴"),
    ("heart", "爱心"),
    ("instant_effect", "瞬间效果"),
    ("large_smoke", "大团烟雾"),
    ("note", "音符"),
    ("poof", "消散"),
    ("portal", "传送门"),
    ("rain", "雨滴"),
    ("sculk_charge", "幽匿蓄力"),
    ("sculk_soul", "幽匿灵魂"),
    ("smoke", "烟雾"),
    ("sneeze", "喷嚏"),
    ("snowflake", "雪花"),
    ("soul_fire_flame", "灵魂火"),
    ("spore_blossom", "孢子花"),
    ("squid_ink", "墨汁"),
    ("sweep_attack", "横扫"),
    ("underwater", "水下"),
    ("vibration", "振动"),
    ("wax_off", "除蜡"),
    ("wax_on", "打蜡"),
    // ── 物品栏槽位 ──
    ("weapon", "武器槽"),
    ("weapon.mainhand", "主手武器槽"),
    ("weapon.offhand", "副手槽"),
    ("armor.head", "头盔槽"),
    ("armor.chest", "胸甲槽"),
    ("armor.legs", "护腿槽"),
    ("armor.feet", "靴子槽"),
    ("armor.body", "挽具槽"),
    ("enderchest", "末影箱"),
    ("hotbar", "快捷栏"),
    ("container", "容器"),
    ("inventory", "物品栏"),
    // ── 音效（ID 用 `.` 分隔，按整条匹配） ──
    ("ambient.cave", "洞穴环境音"),
    ("ambient.underwater.enter", "入水声"),
    ("ambient.underwater.exit", "出水声"),
    ("block.anvil.use", "使用铁砧"),
    ("block.beacon.activate", "信标激活"),
    ("block.bell.use", "敲钟"),
    ("block.chest.close", "关闭箱子"),
    ("block.chest.open", "打开箱子"),
    ("block.enchantment_table.use", "使用附魔台"),
    ("block.end_portal.spawn", "末地传送门生成"),
    ("block.fire.extinguish", "火焰熄灭"),
    ("block.glass.break", "玻璃破碎"),
    ("block.grindstone.use", "使用砂轮"),
    ("block.note_block.bass", "音符盒（贝斯）"),
    ("block.note_block.harp", "音符盒（竖琴）"),
    ("block.note_block.pling", "音符盒（拨弦）"),
    ("block.portal.travel", "穿越传送门"),
    ("block.respawn_anchor.deplete", "重生锚耗尽"),
    ("block.trial_spawner.ambient", "试炼刷怪笼环境音"),
    ("entity.blaze.shoot", "烈焰人喷射"),
    ("entity.cat.ambient", "猫叫声"),
    ("entity.creeper.primed", "苦力怕引信嘶嘶声"),
    ("entity.ender_dragon.growl", "末影龙咆哮"),
    ("entity.experience_orb.pickup", "拾取经验球"),
    ("entity.ghast.shoot", "恶魂发射火球"),
    ("entity.generic.explode", "爆炸"),
    ("entity.item.pickup", "拾取物品"),
    ("entity.piglin.admiring_item", "猪灵赞叹物品"),
    ("entity.player.attack.crit", "暴击"),
    ("entity.player.hurt", "玩家受伤"),
    ("entity.player.levelup", "玩家升级"),
    ("entity.sheep.ambient", "羊叫声"),
    ("entity.villager.no", "村民拒绝"),
    ("entity.villager.yes", "村民同意"),
    ("entity.wither.spawn", "凋灵生成"),
    ("entity.wolf.ambient", "狼叫声"),
    ("entity.zombie.ambient", "僵尸低吼"),
    ("item.goat_horn.play", "山羊角吹响"),
    ("item.totem.use", "图腾触发"),
    ("item.trident.thunder", "三叉戟引雷"),
    ("music.creative", "创造模式音乐"),
    ("music.game", "游戏背景音乐"),
    ("music.menu", "菜单音乐"),
    ("ui.button.click", "按钮点击"),
    ("ui.toast.challenge_complete", "挑战完成提示音"),
    ("weather.rain.above", "雨声"),
    // ── 其他关键字 ──
    ("mainhand", "主手"),
    ("offhand", "副手"),
    ("hand", "手"),
    ("value", "值"),
    ("max", "上限"),
    ("amount", "数值"),
    ("distance", "距离"),
    ("buffer", "缓冲"),
    ("warning", "警告"),
    ("time", "时间"),
    ("center", "中心"),
    ("damage", "伤害"),
    ("progress", "进度条"),
    ("notched_6", "6 段刻度"),
    ("notched_10", "10 段刻度"),
    ("notched_12", "12 段刻度"),
    ("notched_20", "20 段刻度"),
    ("sidebar", "侧边栏"),
    ("list", "玩家列表"),
    ("integer", "整数"),
    ("hearts", "心形"),
    ("styled", "样式化"),
    ("blank", "空白"),
    ("fixed", "固定"),
    ("masked", "仅非空气方块"),
    ("belowName", "名称下方"),
    ("dummy", "虚拟"),
    ("trigger", "触发器"),
    ("deathCount", "死亡次数"),
    ("playerKillCount", "击杀玩家数"),
    ("totalKillCount", "击杀总数"),
    ("health", "生命值"),
    ("food", "饥饿值"),
    ("air", "氧气值"),
    ("armor", "护甲值"),
    ("level", "等级"),
    ("xp", "经验"),
    ("master", "主音量"),
    ("music", "音乐"),
    ("record", "唱片"),
    ("weather", "天气"),
    ("hostile", "敌对生物"),
    ("neutral", "中立生物"),
    ("player", "玩家"),
    ("ambient", "环境"),
    ("voice", "语音"),
    ("add_value", "加法"),
    ("add_multiplied_base", "乘法（基础）"),
    ("add_multiplied_total", "乘法（总和）"),
    ("structure", "结构"),
    ("biome", "生物群系"),
    ("feature", "地物"),
    ("everything", "全部"),
    ("only", "指定"),
    ("grant", "授予"),
    ("revoke", "撤销"),
    ("merge", "合并"),
    ("replace", "替换"),
    ("destroy", "破坏"),
    ("hollow", "挖空"),
    ("keep", "保留"),
    ("outline", "轮廓"),
    ("force", "强制"),
    ("move", "移动"),
    ("normal", "普通"),
    ("points", "经验点"),
    ("levels", "等级"),
    ("subtitle", "副标题"),
    ("actionbar", "快捷栏上方"),
    ("title", "标题"),
    ("times", "时长"),
    ("mount", "骑乘"),
    ("dismount", "下坐骑"),
    ("show", "显示"),
    ("dialog", "对话框"),
    ("village", "村庄"),
    ("mansion", "林地府邸"),
    ("woodland_mansion", "林地府邸"),
    ("monument", "海底神殿"),
    ("stronghold", "要塞"),
    ("fortress", "下界要塞"),
    ("end_city", "末地城"),
    ("buried_treasure", "埋藏的宝藏"),
    ("shipwreck", "沉船"),
    ("pillager_outpost", "掠夺者前哨站"),
    ("ruined_portal", "废弃传送门"),
    ("ancient_city", "远古城市"),
    ("trail_ruins", "古迹废墟"),
    ("trial_chambers", "试炼密室"),
    ("ocean_ruin", "海底废墟"),
    ("desert_pyramid", "沙漠神殿"),
    ("jungle_temple", "丛林神庙"),
    ("swamp_hut", "沼泽小屋"),
    ("igloo", "雪屋"),
    ("mineshaft", "废弃矿井"),
    ("bastion_remnant", "堡垒遗迹"),
    ("nether_fossil", "下界化石"),
    ("plains", "平原"),
    ("desert", "沙漠"),
    ("badlands", "恶地"),
    ("savanna", "热带草原"),
    ("taiga", "针叶林"),
    ("snowy_taiga", "积雪针叶林"),
    ("snowy_plains", "积雪平原"),
    ("cherry_grove", "樱花树林"),
    ("mangrove_swamp", "红树林沼泽"),
    ("deep_dark", "深暗之域"),
    ("lush_caves", "繁茂洞穴"),
    ("dripstone_caves", "溶洞"),
    ("mushroom_fields", "蘑菇岛"),
    ("flower_forest", "繁花森林"),
    ("birch_forest", "白桦森林"),
    ("dark_forest", "黑森林"),
    ("swamp", "沼泽"),
    ("beach", "沙滩"),
    ("ocean", "海洋"),
    ("deep_ocean", "深海"),
    ("frozen_peaks", "冰封山峰"),
    ("jagged_peaks", "尖峭山峰"),
    ("stony_peaks", "裸岩山峰"),
    ("meadow", "草甸"),
    ("grove", "雪林"),
    ("river", "河流"),
    ("forest", "森林"),
    ("ice_spikes", "冰刺之地"),
    ("the_end", "末地"),
    ("nether_wastes", "下界荒地"),
    ("soul_sand_valley", "灵魂沙峡谷"),
    ("crimson_forest", "绯红森林"),
    ("warped_forest", "诡异森林"),
    ("basalt_deltas", "玄武岩三角洲"),
    ("pale_garden", "苍白之园"),
    // ── 生物 ──
    ("zombie", "僵尸"),
    ("skeleton", "骷髅"),
    ("creeper", "苦力怕"),
    ("spider", "蜘蛛"),
    ("cave_spider", "洞穴蜘蛛"),
    ("enderman", "末影人"),
    ("witch", "女巫"),
    ("magma_cube", "岩浆怪"),
    ("blaze", "烈焰人"),
    ("ghast", "恶魂"),
    ("wither_skeleton", "凋灵骷髅"),
    ("piglin_brute", "猪灵蛮兵"),
    ("piglin", "猪灵"),
    ("hoglin", "疣猪兽"),
    ("zoglin", "僵尸疣猪兽"),
    ("husk", "尸壳"),
    ("stray", "流浪者"),
    ("drowned", "溺尸"),
    ("phantom", "幻翼"),
    ("silverfish", "蠹虫"),
    ("endermite", "末影螨"),
    ("elder_guardian", "远古守卫者"),
    ("guardian", "守卫者"),
    ("shulker", "潜影贝"),
    ("vex", "恼鬼"),
    ("vindicator", "卫道士"),
    ("evoker", "唤魔者"),
    ("illusioner", "幻术师"),
    ("pillager", "掠夺者"),
    ("ravager", "劫掠兽"),
    ("warden", "监守者"),
    ("breeze", "旋风人"),
    ("bogged", "沼骸"),
    ("creaking", "嘎枝"),
    ("ender_dragon", "末影龙"),
    ("cow", "牛"),
    ("mooshroom", "哞菇"),
    ("pig", "猪"),
    ("sheep", "羊"),
    ("horse", "马"),
    ("skeleton_horse", "骷髅马"),
    ("zombie_horse", "僵尸马"),
    ("donkey", "驴"),
    ("mule", "骡"),
    ("llama", "羊驼"),
    ("trader_llama", "行商羊驼"),
    ("wolf", "狼"),
    ("cat", "猫"),
    ("ocelot", "豹猫"),
    ("fox", "狐狸"),
    ("bee", "蜜蜂"),
    ("villager", "村民"),
    ("zombie_villager", "僵尸村民"),
    ("wandering_trader", "流浪商人"),
    ("iron_golem", "铁傀儡"),
    ("snow_golem", "雪傀儡"),
    ("copper_golem", "铜傀儡"),
    ("allay", "悦灵"),
    ("sniffer", "嗅探兽"),
    ("camel", "骆驼"),
    ("armadillo", "犰狳"),
    ("goat", "山羊"),
    ("frog", "青蛙"),
    ("tadpole", "蝌蚪"),
    ("axolotl", "美西螈"),
    ("bat", "蝙蝠"),
    ("squid", "鱿鱼"),
    ("glow_squid", "发光鱿鱼"),
    ("dolphin", "海豚"),
    ("turtle", "海龟"),
    ("panda", "熊猫"),
    ("polar_bear", "北极熊"),
    ("parrot", "鹦鹉"),
    ("strider", "炽足兽"),
    ("happy_ghast", "快乐恶魂"),
    ("zombified_piglin", "僵尸猪灵"),
    ("spawn_egg", "刷怪蛋"),
    // ── 非生物实体 ──
    ("minecart", "矿车"),
    ("chest_minecart", "运输矿车"),
    ("hopper_minecart", "漏斗矿车"),
    ("furnace_minecart", "动力矿车"),
    ("tnt_minecart", "TNT 矿车"),
    ("item", "物品"),
    ("experience_orb", "经验球"),
    ("lightning_bolt", "闪电"),
    ("area_effect_cloud", "区域效果云"),
    ("falling_block", "下落的方块"),
    ("marker", "标记"),
    ("display", "展示实体"),
    ("interaction", "交互实体"),
    ("fishing_bobber", "浮漂"),
    ("leash_knot", "拴绳结"),
    ("fireball", "火球"),
    ("small_fireball", "小火球"),
    ("dragon_fireball", "末影龙火球"),
    ("wither_skull", "凋灵之首"),
    ("snowball", "雪球"),
    ("wind_charge", "风弹"),
];

/// 把一个参数翻成中文：选择器、枚举关键字、物品/方块/实体 ID 都走这里。
///
/// 认不出来就原样返回，绝不丢信息。
pub(crate) fn localize(arg: &str) -> String {
    if arg.is_empty() {
        return String::new();
    }

    // 目标选择器（可能带 `[type=...]` 之类）
    if arg.starts_with('@') {
        return selector(arg);
    }

    // 物品栈：`diamond_sword[...]` / `diamond_sword{...}`
    // ID 翻成中文，附加数据原样跟在后面。
    if let Some(i) = arg.find(|c| c == '[' || c == '{') {
        let (id, data) = arg.split_at(i);
        return match translate_id(id) {
            Some(zh) => format!("{zh}{data}"),
            None => arg.to_string(),
        };
    }

    translate_id(arg).unwrap_or_else(|| arg.to_string())
}

/// 目标选择器：`@a` → 所有玩家；`@e[type=zombie]` → 所有实体[type=僵尸]；
/// 玩家名之类的普通名字原样返回。
fn selector(arg: &str) -> String {
    let (head, rest) = match arg.find('[') {
        Some(i) => (&arg[..i], &arg[i..]),
        None => (arg, ""),
    };

    let base = SELECTORS
        .iter()
        .find(|(k, _)| *k == head)
        .map(|(_, v)| (*v).to_string());

    match base {
        None => arg.to_string(),
        Some(name) => {
            if rest.is_empty() {
                return name;
            }
            let inner = rest.trim_start_matches('[').trim_end_matches(']');
            let translated: Vec<String> = inner
                .split(',')
                .map(|kv| match kv.split_once('=') {
                    Some((k, v)) => format!("{}={}", k.trim(), localize(v.trim())),
                    None => kv.trim().to_string(),
                })
                .collect();
            format!("{name}[{}]", translated.join(", "))
        }
    }
}

/// 按 `_` 贪心合并相邻词后翻译；一个词都没认出来就返回 None。
fn translate_id(id: &str) -> Option<String> {
    let parts: Vec<&str> = id.split('_').collect();
    let mut out: Vec<String> = Vec::new();
    let mut i = 0usize;
    let mut matched = false;

    while i < parts.len() {
        // 从最长组合往下试，`light_blue` 优先于 `light` + `blue`
        let limit = MAX_PARTS.min(parts.len() - i);
        let mut hit: Option<(usize, &'static str)> = None;
        for n in (1..=limit).rev() {
            let candidate = parts[i..i + n].join("_");
            if let Some(zh) = lookup(&candidate) {
                hit = Some((n, zh));
                break;
            }
        }

        match hit {
            Some((n, zh)) => {
                out.push(zh.to_string());
                i += n;
                matched = true;
            }
            None => {
                out.push(parts[i].to_string());
                i += 1;
            }
        }
    }

    if matched {
        Some(out.concat())
    } else {
        None
    }
}

/// 词典的哈希索引。
///
/// 补全时可能一次要翻译上千个候选（`/give @a ` 会列出全部物品），
/// 线性扫描整张词典太慢，所以首次使用时建一次索引。
static INDEX: OnceLock<HashMap<&'static str, &'static str>> = OnceLock::new();

fn lookup(word: &str) -> Option<&'static str> {
    INDEX
        .get_or_init(|| DICT.iter().copied().collect())
        .get(word)
        .copied()
}
