// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `absolute_span`, `advance`, `analyze_execute`, `arg`, `build_usage`, `check_execute_clauses`, `commands`, `describe_node`, `describe`, `enum_values`, `execute_clause_expect`, `execute_execute`, `execute_message`, `first_error_result`, `is_selector`, `lit`, `locate_cursor`, `node_candidates`, `opt`, `pos3`, `semantic_check`, `tokenize`, `validate_arg`, `validate_id`, `validate_slot`, `validate_word`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ArgType`, `Cmd`, `Node`, `Token`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`

/// 实时分析输入：补全建议 + 语法错误 + 光标提示
Future<AnalysisResult> analyze({required String input, required int cursor}) =>
    RustLib.instance.api.crateApiMinecraftAnalyze(input: input, cursor: cursor);

/// 执行指令（模拟），返回成功/失败与反馈消息
Future<ExecutionResult> execute({required String input}) =>
    RustLib.instance.api.crateApiMinecraftExecute(input: input);

/// 指令面板数据
Future<List<CommandInfo>> listCommands() =>
    RustLib.instance.api.crateApiMinecraftListCommands();

/// 输入分析结果
class AnalysisResult {
  final List<Suggestion> suggestions;
  final List<SyntaxError> errors;

  /// 当前输入是否为一条完整、可执行的指令
  final bool complete;

  /// 光标处期望参数的中文提示
  final String hint;

  /// 当前指令的用法示例
  final String usage;

  /// 光标所在 token 的起始索引（用于补全替换）
  final int replaceStart;

  const AnalysisResult({
    required this.suggestions,
    required this.errors,
    required this.complete,
    required this.hint,
    required this.usage,
    required this.replaceStart,
  });

  @override
  int get hashCode =>
      suggestions.hashCode ^
      errors.hashCode ^
      complete.hashCode ^
      hint.hashCode ^
      usage.hashCode ^
      replaceStart.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisResult &&
          runtimeType == other.runtimeType &&
          suggestions == other.suggestions &&
          errors == other.errors &&
          complete == other.complete &&
          hint == other.hint &&
          usage == other.usage &&
          replaceStart == other.replaceStart;
}

/// 指令信息（用于指令面板）
class CommandInfo {
  final String name;
  final List<String> aliases;
  final String usage;
  final String description;
  final bool opOnly;

  const CommandInfo({
    required this.name,
    required this.aliases,
    required this.usage,
    required this.description,
    required this.opOnly,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      aliases.hashCode ^
      usage.hashCode ^
      description.hashCode ^
      opOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommandInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          aliases == other.aliases &&
          usage == other.usage &&
          description == other.description &&
          opOnly == other.opOnly;
}

/// 执行结果
class ExecutionResult {
  final bool success;
  final String message;

  const ExecutionResult({required this.success, required this.message});

  @override
  int get hashCode => success.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExecutionResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message;
}

/// 一条补全建议
class Suggestion {
  /// 插入到输入框的文本
  final String insert;

  /// 显示的主要文本
  final String label;

  /// 显示的说明文字
  final String detail;

  /// 插入后是否自动补一个空格
  final bool appendSpace;

  const Suggestion({
    required this.insert,
    required this.label,
    required this.detail,
    required this.appendSpace,
  });

  @override
  int get hashCode =>
      insert.hashCode ^ label.hashCode ^ detail.hashCode ^ appendSpace.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Suggestion &&
          runtimeType == other.runtimeType &&
          insert == other.insert &&
          label == other.label &&
          detail == other.detail &&
          appendSpace == other.appendSpace;
}

/// 一条语法错误（带字符区间，可用来在输入框下标红）
class SyntaxError {
  final String message;

  /// 起始字符索引（char 计数，从 0 开始）
  final int start;

  /// 结束字符索引（不含）
  final int end;

  const SyntaxError({
    required this.message,
    required this.start,
    required this.end,
  });

  @override
  int get hashCode => message.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyntaxError &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          start == other.start &&
          end == other.end;
}
